"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
scan_timeout = 30
command_timeout = 500

format = """
[â–‘â–’â–“](#7aa2f7)\
[ ïŒ† ](bg:#7aa2f7 fg:#15161e)\
[î‚´](fg:#7aa2f7 bg:#3b4261)\
$hostname\
$directory\
[î‚´](fg:#3b4261 bg:#292e42)\
$git_branch\
$git_status\
[î‚´](fg:#292e42 bg:#1f2335)\
$cmd_duration\
$nodejs\
$rust\
$golang\
$php\
$python\
$docker_context\
[î‚´](fg:#1f2335)\
\n$character"""

[hostname]
ssh_only = true
ssh_symbol = "ğŸŒ "
style = "fg:#c0caf5 bg:#3b4261"
format = "[ $ssh_symbol$hostname ]($style)"

[directory]
style = "fg:#c0caf5 bg:#3b4261"
format = "[ $path$read_only ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"
read_only = " ï€£"

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

[git_branch]
symbol = "ï˜"
style = "fg:#7aa2f7 bg:#292e42"
format = "[ $symbol $branch ]($style)"

[git_status]
style = "fg:#bb9af7 bg:#292e42"
format = "[ $all_status$ahead_behind ]($style)"

[cmd_duration]
min_time = 2000
style = "fg:#bb9af7 bg:#1f2335"
format = "[ â± $duration ]($style)"

[nodejs]
symbol = "îœ˜"
style = "fg:#7aa2f7 bg:#1f2335"
format = "[ $symbol ($version) ]($style)"

[rust]
symbol = "î¨"
style = "fg:#7aa2f7 bg:#1f2335"
format = "[ $symbol ($version) ]($style)"

[golang]
symbol = "î˜§"
style = "fg:#7aa2f7 bg:#1f2335"
format = "[ $symbol ($version) ]($style)"

[php]
symbol = "î˜ˆ"
style = "fg:#7aa2f7 bg:#1f2335"
format = "[ $symbol ($version) ]($style)"

[python]
symbol = "ğŸ"
style = "fg:#7aa2f7 bg:#1f2335"
format = "[ $symbol ($version) ]($style)"

[docker_context]
symbol = "ïŒˆ "
style = "fg:#7aa2f7 bg:#1f2335"
format = "[ $symbol $context ]($style)"

[character]
success_symbol = "[âœ](bold #7aa2f7)"
error_symbol = "[âœ—](bold #f7768e)"
